name: Build and Release Firmware

on:
  push:
    tags:
      - 'Release-*'
      - 'PreRelease-*'
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set working directory to firmware
        run: cd firmware
      
      - name: Install Python and PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          pip install platformio
          
      - name: Build firmware
        run: |
          cd firmware
          pio run
       
      - name: Convert ELF to UF2
        run: |
          cd firmware/elf2uf2
          make build
          ./elf2uf2 ../.pio/build/pico/APPLICATION.elf ../.pio/build/pico/APPLICATION.uf2

     
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-uf2
          path: firmware/.pio/build/**/*.uf2
          
     
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for gh CLI context
        uses: actions/checkout@v4 

      - name: Download UF2 artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware-uf2
          path: ./release


      - name: Extract Tag Name
        id: extract_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create or Update Release and Upload Asset
        run: |
          TAG_NAME="${{ env.RELEASE_TAG }}"
          FILE_PATH="./release/pico/APPLICATION.uf2" 

          FLAGS=""
          if [[ "$TAG_NAME" == PreRelease-* ]]; then
            FLAGS="--draft --prerelease"
          fi
          echo "Creating release $TAG_NAME with flags: $FLAGS"
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            $FLAGS \
            --notes "Automated build [ci skip]"
          gh release upload "$TAG_NAME" "$FILE_PATH" --clobber

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

